import type { Metadata } from "next";
import "./globals.scss";
import { Black_Ops_One, Lexend } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import 'react-perfect-scrollbar/dist/css/styles.css';
import HeaderComponent from "@/components/header/HeaderComponent";

const blackOpsOne = Black_Ops_One({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-black-ops-one',
})

const lexend = Lexend({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-lexend',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  return (
    <html lang="en">
      <body className={`${blackOpsOne.variable} ${lexend.variable}`}>
        <HeaderComponent />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
